local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

  #  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  #  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>

amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  region: eu-west-2
  bucket: comunidad-vecinos.herokuapp.com